In [21]:
import numpy as np
A = np.array([[-1,2,3],[0,3,-1],[2,-2,5]])
B = np.array([[0,4,-2],[2,-1,3],[3,2,-4]])
C = np.array([[-2,3,-1],[0,-1,2],[1,0,0]])

In [24]:
# (a) 2𝑨2 −3𝑩+𝑪 

print("a)\n",2*(A@A)-3*B+C)

# (b) 2𝑨2 −3𝑨𝑩+𝑨𝑪 

print("b)\n",2*(A@A)-3*(A@B)+(A@C))

# (c) 2𝑨2𝑩−3𝑨𝑩2 +𝑨𝑪𝑩 

print("c)\n",2*(A@A)@B-3*(A@(B@B))+(A@C@B))

# (d) 𝑨2 +𝑨𝑪−𝑩𝑨−𝑩𝑪

print("d)\n",(A@A)+(A@C)-(B@A)+(B@C))

a)
 [[ 12 -13  25]
 [-10  24 -23]
 [  8 -30  78]]
b)
 [[-20  -9  37]
 [-14  34 -49]
 [-16 -76 150]]
c)
 [[  93    3 -135]
 [ -79 -188  326]
 [ 298  312 -796]]
d)
 [[ 14 -27  37]
 [ -8  20 -28]
 [ 10 -17  41]]


In [13]:
A = np.array([[2,-3,4],[0,0,1],[-1,2,3]])
B = np.array([[-1,0,5],[2,3,4],[-2,0,1]])

In [28]:
# (a)  𝑨𝑡 
print("a)\n", A.T )

# (b)  𝑩𝑡 
print("b)\n", B.T )

# (c)  𝟐𝑨𝑡 
print("c)\n", 2*A.T )

# (d)  (𝟐𝑨)𝑡 
print("d)\n", (2*A).T )

# (e)  𝑨𝑡 + 𝑩𝑡 
print("e)\n", A.T + B.T )

# (f) (𝑨+𝑩)𝑡
print("f)\n", (A + B).T )


a)
 [ 2 -3  0]
b)
 [4 3 1]
c)
 [ 4 -6  0]
d)
 [ 4 -6  0]
e)
 [6 0 1]
f)
 [6 0 1]


In [25]:
A = np.array([-1,0,2])

In [26]:
# (a)  𝑨 ∙𝑨𝑡 
print("a)\n", A @ A.T )

# (b)  𝑨𝑡 ∙𝑨
print("b)\n", A.T @ A )

a)
 5
b)
 5


In [38]:
A = np.array([[2],[-3],[0]])
B = np.array([[4],[3],[1]])

In [39]:
# (a)  𝑨 ∙𝑩𝑡  
print("a)\n", A @ B.T )

# (b)  𝑩 ∙𝑨𝑡 
print("b)\n", B @ A.T )

# (c)  𝑩𝑡 ∙𝑨 
print("c)\n", B.T @ A )

# (d)  𝑨 ∙𝑨𝑡 
print("d)\n", A @ A.T )

# (e)  𝑨𝑡 ∙𝑨 
print("e)\n", A.T @ A)

# (f) (𝑨𝑡 ∙𝑩)𝑨
print("f)\n", (A.T @ B) @ A)
# habria que trasponer en algun punto otra vez

a)
 [[  8   6   2]
 [-12  -9  -3]
 [  0   0   0]]
b)
 [[  8 -12   0]
 [  6  -9   0]
 [  2  -3   0]]
c)
 [[-1]]
d)
 [[ 4 -6  0]
 [-6  9  0]
 [ 0  0  0]]
e)
 [[13]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [40]:
A = np.array([[1,2],[1,2]])
B = np.array([[3,5],[3,5]])
C = np.array([[3,5],[3,5]])

In [46]:
print(A@B == A@C)
print((A@B)@ np.linalg.inv(A) == (A@C)@ np.linalg.inv(A))

[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]


In [57]:
A = np.array([[1,-1],[2,3]])

A1=np.linalg.inv(A)
print(A1)

A = np.array([[1,0,2],[0,-2,1],[0,1,-1]])

A1=np.linalg.inv(A)
print(A1)

A = np.array([[1,1,1,1],[0,1,-1,2],[0,0,2,1],[0,0,0,3]])

A1=np.linalg.inv(A)
print(A1)




[[ 0.6  0.2]
 [-0.4  0.2]]
[[ 1.  2.  4.]
 [-0. -1. -1.]
 [-0. -1. -2.]]
[[ 1.         -1.         -1.          0.66666667]
 [ 0.          1.          0.5        -0.83333333]
 [ 0.          0.          0.5        -0.16666667]
 [ 0.          0.          0.          0.33333333]]


In [73]:
A = np.array([[1,2,-1],[-2,1,0],[4,2,-3]])
print(round(np.linalg.det(A),1) == -7)

A = np.array([[0,-1,2],[2,-3,4],[1,2,5]])
print(round(np.linalg.det(A),1) == 0)

A = np.array([[2,5,3],[4,10,6],[6,4,7]])
print(round(np.linalg.det(A),1) == 0)

A = np.array([[1,0,0,-1],[2,3,4 ,7],[-3,4,5,9],[-4,-5,6,1]])
print(round(np.linalg.det(A),1) == 216)

A = np.array([[3,-1,5,2],[2,0,7 ,0],[-3,1,2,0],[5,-4,1,2]])
print(round(np.linalg.det(A),1) == -106)

True
False
True
True
True


In [79]:
#  Sean A, B y C matrices cuadradas de orden 3, tales que |𝐴| = 3, |𝐵| = 2, |𝐶| = 0 
# a) |5𝐴| b) |1/2 𝐵| c) |𝐴𝑡𝐵−1| d) |𝐴𝐵𝐴−1𝐵| 
print((5**3)*3)     #se eleva el 5 por el det y el resul por el det otra vez
print((0.5**2)*2)   #igual que el anterior
print(3*1/2)        #det de tras igual al normal y la inv 1 entre det
print(3*2*1/3*2)    #igual que el anterior

375
0.5
1.5
4.0


In [81]:
A = np.array([[2,2,3],[2,1,3],[1,1,2]])
np.linalg.matrix_rank(A)

E = np.array([[1,1,1,1,2],[1,2,1,2,1],[0,1,0,1,0],[1,0,1,0,2]])
np.linalg.matrix_rank(E)

3

In [82]:
A = np.array([[1, -1],
              [0, 1]])

B = np.array([[1, -1],
              [-1, 1]])

# Encontrar los autovalores y autovectores de A
autovalores_A, autovectores_A = np.linalg.eig(A)

# Encontrar los autovalores y autovectores de B
autovalores_B, autovectores_B = np.linalg.eig(B)

# Verificar si A es diagonalizable
diagonalizable_A = np.all(np.linalg.eigvals(A) == autovalores_A)
print("¿A es diagonalizable?", diagonalizable_A)

# Verificar si B es diagonalizable
diagonalizable_B = np.all(np.linalg.eigvals(B) == autovalores_B)
print("¿B es diagonalizable?", diagonalizable_B)

¿A es diagonalizable? True
¿B es diagonalizable? True
