In [3]:
import numpy as np



In [24]:
# (A- lI)*v = 0
A = [[50,25,25],[10,85,5],[15,15,70]]

aval, avec = np.linalg.eig(A)

# Mostrar los resultados
print("Autovalores:", aval)
print("Autovectores:")
print(avec)


Autovalores: [ 36.49218941 100.          68.50781059]
Autovectores:
[[ 0.92571056 -0.57735027  0.40303394]
 [-0.155288   -0.57735027 -0.48051719]
 [-0.34488491 -0.57735027  0.77888823]]


In [27]:
# (A- lI)*v = 0
A = [[50,10,15],[25,85,15],[25,5,70]]

aval, avec = np.linalg.eig(A)

# Mostrar los resultados
print("Autovalores:", aval)
print("Autovectores:")
print(avec)


Autovalores: [ 36.49218941 100.          68.50781059]
Autovectores:
[[ 0.79524162 -0.29138576  0.11292499]
 [-0.23733022 -0.87415728 -0.75677383]
 [-0.5579114  -0.38851434  0.64384884]]


In [ ]:
# suma columna, 1,50.. 0,29

In [44]:
suma = np.sum(avec[:, 1]) #suma de los autovalores del autovector
suma2 = np.sum(avec[:, 1]/suma) # total de los pocentajes ()=)1

for i,em in zip(range(len(avec[:,1])),["A","B","C"]):
    e = avec[:,1][i] / suma
    print("En la normalizacion,",em,"tendra un",round(e*100,2),"% de la clientela")

En la normalizacion, A tendra un 18.75 % de la clientela
En la normalizacion, B tendra un 56.25 % de la clientela
En la normalizacion, C tendra un 25.0 % de la clientela
